import Head from 'next/head'
import Header from './compo/Header';
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Index() {
  let row = []
  for(let i=0;i<8;i++) row.push(<div className={styles.store__box}>
      <div className={styles.store__image}></div>
      <div className={styles.store__title}>Kentski</div>
      <div className={styles.store__description}>sinj autiste</div>
      <button className={styles.store__btn}>Add to cart</button>
  </div>)
  return (
    <>
      <Head>
        <title>Store | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <div className={styles.container}>
            <div className={styles.header +" "+ styles.flex}>
                <div className={styles.flex__1 + " "+ styles.container}>
                    <h1>Welcome to Nword.store</h1>
                    <p>Achète ton Nword-pass dès à présent mon gar</p>
                    <Link href="/store"><a className={styles.action__btn}>Shop</a></Link>
                </div>
                <div className={styles.flex__1}>
                    <div className={styles.header__box}>
                        <h1 className={styles.header__item__title}>Nword 70% Kentski</h1>
                        <div className={styles.header__item__image}></div>
                        <button className={styles.store__btn}>Add to cart</button>
                    </div>
                </div>   
            </div>
            <div className={styles.topic__grid}>
                <div className={styles.topic__box}>Themes</div>
                <div className={styles.topic__box}>Bio</div>
                <div className={styles.topic__box}>Usernames</div>
                <div className={styles.topic__box}>Banners</div>
                <div className={styles.topic__box}>Servers</div>
                <div className={styles.topic__box + " "+ styles.topic__box__active}>Avatars</div>
                <div className={styles.topic__box}>Lorem</div>
                <div className={styles.topic__box}>Ipsum</div>
            </div>
            <div className={styles.store__grid}>
                {row}
            </div>
            <button className={styles.store__btn} style={{width: 200, margin: "0 auto"}}>See more</button>
            <div className={styles.action__box +" "+ styles.flex}>
                <div className={styles.flex__1 +" "+ styles.container}>
                    <h1>Discover more items</h1>
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                    <Link href="/store"><a className={styles.action__btn}>Shop</a></Link>
                </div>
                <div className={styles.flex__1}></div>
            </div>
        </div>
            <footer className={styles.footer}>
                <h4>Nword.store</h4>
            </footer></>
  )
}
